// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage/CinematicSplit": () => import("../components/mockups/homepage/CinematicSplit"),
  "./components/mockups/homepage/PremiumDark": () => import("../components/mockups/homepage/PremiumDark"),
  "./components/mockups/homepage/VehicleDetail": () => import("../components/mockups/homepage/VehicleDetail")
};
