// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/eu-home/Constellation.tsx": () => import("../components/mockups/eu-home/Constellation.tsx"),
  "./components/mockups/eu-home/Current.tsx": () => import("../components/mockups/eu-home/Current.tsx"),
  "./components/mockups/eu-home/GoldenHour.tsx": () => import("../components/mockups/eu-home/GoldenHour.tsx"),
  "./components/mockups/eu-home/Redesign.tsx": () => import("../components/mockups/eu-home/Redesign.tsx"),
  "./components/mockups/eu-home/Route.tsx": () => import("../components/mockups/eu-home/Route.tsx"),
  "./components/mockups/eu-home/Showroom.tsx": () => import("../components/mockups/eu-home/Showroom.tsx"),
  "./components/mockups/homepage/CinematicSplit.tsx": () => import("../components/mockups/homepage/CinematicSplit.tsx"),
  "./components/mockups/homepage/PremiumDark.tsx": () => import("../components/mockups/homepage/PremiumDark.tsx"),
  "./components/mockups/homepage/VehicleDetail.tsx": () => import("../components/mockups/homepage/VehicleDetail.tsx")
};
