import { useState } from "react";

type Vehicle = {
  name: string;
  subtitle: string;
  price: string;
  image: string;
  detail: string;
};

const vehicles: Vehicle[] = [
  { name: "Porsche 911 Carrera", subtitle: "Coupé · 2021 · 31 240 km", price: "89 500 €", image: "/__mockup/images/eu-home/car-2.png", detail: "Bleu Gentiane, intérieur cuir naturel" },
  { name: "BMW M4 Competition", subtitle: "Berline · 2022 · 18 600 km", price: "59 900 €", image: "/__mockup/images/eu-home/car-1.jpeg", detail: "Brooklyn Grey, boîte automatique" },
  { name: "Mercedes-AMG GT", subtitle: "Coupé · 2020 · 24 980 km", price: "74 900 €", image: "/__mockup/images/eu-home/car-3.png", detail: "Obsidian Black, pack Premium Plus" },
];

export default function LuxembourgShowroom() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [active, setActive] = useState("La sélection");
  const [selected, setSelected] = useState<Vehicle | null>(null);
  const [appointment, setAppointment] = useState(false);
  const [sent, setSent] = useState(false);

  const openAppointment = () => {
    setSelected(null);
    setAppointment(true);
    setSent(false);
  };

  return (
    <div className="lux" id="top">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&family=Instrument+Serif:ital@0;1&display=swap');
        .lux{--ink:#252d2e;--stone:#e7e1d7;--sand:#f4f0e9;--line:#cbc5bb;--rust:#a25842;--sage:#65756c;background:var(--sand);color:var(--ink);min-height:100vh;font-family:'DM Sans',sans-serif;letter-spacing:-.01em}
        .lux *{box-sizing:border-box}.lux a{color:inherit;text-decoration:none}.lux button{font:inherit;color:inherit;cursor:pointer}.lux a.lux-button{color:var(--sand)}.lux a.lux-button.ghost{color:var(--ink)}
        .lux-header{height:78px;padding:0 clamp(22px,5vw,74px);display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid rgba(37,45,46,.16);background:rgba(244,240,233,.9);position:relative;z-index:5}
        .lux-brand{display:flex;align-items:center;gap:13px;font-size:11px;letter-spacing:.17em;text-transform:uppercase;font-weight:600}.lux-mark{width:29px;height:29px;border:1px solid var(--ink);border-radius:50%;display:grid;place-items:center;font-family:Georgia,serif;font-size:16px;letter-spacing:0}.lux-nav{display:flex;gap:34px;font-size:12px;color:#58605c}.lux-nav a:hover{text-decoration:underline;text-underline-offset:5px}.lux-header-actions{display:flex;align-items:center;gap:20px}.lux-lang{background:none;border:0;font-size:11px;letter-spacing:.12em}.lux-visit{border:1px solid var(--ink);background:var(--ink);color:var(--sand)!important;padding:12px 17px;font-size:11px;letter-spacing:.06em}.lux-menu{display:none;background:none;border:0;font-size:22px}
        .lux-hero{min-height:650px;position:relative;display:grid;grid-template-columns:minmax(330px,.86fr) 1.4fr;overflow:hidden;background:#b4afa4}.lux-hero-copy{padding:clamp(65px,9vw,125px) clamp(25px,6vw,100px);background:var(--stone);position:relative;z-index:1}.lux-kicker,.lux-eyebrow{font-size:10px;text-transform:uppercase;letter-spacing:.19em;color:var(--rust);font-weight:600}.lux-hero h1{font-family:'Instrument Serif',Georgia,serif;font-size:clamp(66px,8.4vw,125px);line-height:.86;font-weight:400;letter-spacing:-.055em;margin:29px 0 31px}.lux-hero h1 em{color:var(--rust);font-style:italic}.lux-hero-deck{max-width:330px;font-size:15px;line-height:1.65;color:#4e5753}.lux-hero-actions{display:flex;gap:17px;margin-top:38px;align-items:center}.lux-button{padding:14px 18px;border:1px solid var(--ink);background:var(--ink);color:var(--sand);font-size:11px;letter-spacing:.04em}.lux-button.ghost{background:transparent;color:var(--ink)}.lux-hero-photo{background-image:linear-gradient(90deg,rgba(36,42,42,.16),transparent 45%),url('/__mockup/images/luxembourgshowroom-limestone-hero.png');background-size:cover;background-position:center;min-height:450px}.lux-hero-stamp{position:absolute;right:38px;bottom:31px;color:var(--sand);font-size:10px;letter-spacing:.12em;text-transform:uppercase;writing-mode:vertical-rl;opacity:.85}
        .lux-strip{display:flex;justify-content:space-between;gap:30px;padding:19px clamp(25px,6vw,100px);background:var(--ink);color:#ddd9cf;font-size:11px;letter-spacing:.06em}.lux-strip span{opacity:.65}.lux-strip strong{font-weight:500;color:#f2eee6}
        .lux-intro{padding:112px clamp(25px,10vw,170px) 118px;display:grid;grid-template-columns:1fr 1fr;gap:11vw}.lux-intro h2,.lux-stock h2,.lux-method h2{font-family:'Instrument Serif',Georgia,serif;font-size:clamp(43px,5vw,71px);font-weight:400;line-height:.95;letter-spacing:-.045em;margin:17px 0}.lux-intro h2 em,.lux-method h2 em{color:var(--rust);font-style:italic}.lux-intro-copy{padding-top:44px;max-width:410px;font-size:16px;line-height:1.65;color:#53605a}.lux-intro-copy strong{display:block;color:var(--ink);font-weight:500;margin-top:24px;font-size:14px}.lux-location{margin-top:36px;padding-top:17px;border-top:1px solid var(--line);font-size:11px;display:flex;justify-content:space-between;color:#66706b}
        .lux-stock{padding:75px clamp(25px,6vw,100px) 120px;background:#d7d1c6}.lux-stock-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:35px}.lux-stock-head p{max-width:220px;color:#68706a;font-size:12px;line-height:1.5}.lux-filters{display:flex;gap:10px;margin-bottom:34px}.lux-filter{border:0;border-bottom:1px solid transparent;padding:8px 0;margin-right:23px;background:none;color:#68706a;font-size:12px}.lux-filter.active{color:var(--ink);border-color:var(--rust)}.lux-grid{display:grid;grid-template-columns:1.2fr .9fr .9fr;gap:18px}.lux-card{background:var(--sand);min-width:0}.lux-card:first-child{grid-row:span 2}.lux-visual{height:267px;position:relative;overflow:hidden;background:#b8b4ac}.lux-card:first-child .lux-visual{height:422px}.lux-visual img{width:100%;height:100%;object-fit:cover;transition:transform .5s ease}.lux-card:hover img{transform:scale(1.035)}.lux-card-badge{position:absolute;top:14px;left:14px;background:var(--sand);padding:7px 9px;font-size:9px;text-transform:uppercase;letter-spacing:.11em}.lux-card-body{padding:18px 19px 20px}.lux-card-meta{display:flex;justify-content:space-between;color:#788078;font-size:10px;text-transform:uppercase;letter-spacing:.1em}.lux-card h3{font-family:'Instrument Serif',Georgia,serif;font-size:27px;font-weight:400;margin:12px 0 5px;letter-spacing:-.03em}.lux-card-detail{font-size:11px;color:#748078}.lux-card-foot{display:flex;justify-content:space-between;align-items:end;margin-top:22px}.lux-price{font-size:15px}.lux-more{border:0;border-bottom:1px solid var(--rust);background:none;padding:0 0 3px;font-size:10px;color:var(--rust);letter-spacing:.06em}
        .lux-method{padding:117px clamp(25px,10vw,170px);display:grid;grid-template-columns:.9fr 1.1fr;gap:10vw}.lux-method-list{border-top:1px solid var(--line);margin-top:8px}.lux-method-item{display:grid;grid-template-columns:55px 1fr;padding:25px 0;border-bottom:1px solid var(--line)}.lux-method-item b{font-size:10px;color:var(--rust);font-weight:500}.lux-method-item h3{margin:0 0 7px;font-family:'Instrument Serif',Georgia,serif;font-size:25px;font-weight:400}.lux-method-item p{margin:0;color:#66706b;font-size:13px;line-height:1.55;max-width:370px}
        .lux-quote{padding:100px 25px;background:#65756c;color:#ece8dd;text-align:center}.lux-quote blockquote{font-family:'Instrument Serif',Georgia,serif;font-size:clamp(35px,5vw,66px);line-height:1;max-width:780px;margin:0 auto 22px;letter-spacing:-.04em}.lux-quote cite{font-size:10px;letter-spacing:.16em;text-transform:uppercase;font-style:normal;color:#c9d0c6}.lux-footer{background:var(--ink);color:#e8e1d6;padding:38px clamp(25px,6vw,100px);display:flex;justify-content:space-between;align-items:end}.lux-footer-brand{font-size:11px;letter-spacing:.16em;text-transform:uppercase}.lux-footer small{display:block;margin-top:12px;color:#9da49d;font-size:11px;letter-spacing:0}.lux-footer-links{display:flex;gap:26px;align-items:center;font-size:11px;color:#bec3ba}.lux-footer-links button{border:1px solid #b9c0b6;background:transparent;color:#e8e1d6;padding:10px 14px;font-size:10px;letter-spacing:.06em}
        .lux-modal-backdrop{position:fixed;inset:0;background:rgba(29,35,34,.58);z-index:20;display:grid;place-items:center;padding:20px}.lux-modal{background:var(--sand);width:min(475px,100%);padding:42px;position:relative}.lux-modal h2{font-family:'Instrument Serif',Georgia,serif;font-size:45px;font-weight:400;line-height:.95;margin:17px 0 14px}.lux-modal p{font-size:13px;line-height:1.6;color:#68706a}.lux-modal-close{position:absolute;right:16px;top:12px;background:none;border:0;font-size:25px}.lux-form{display:grid;gap:11px;margin-top:25px}.lux-form input{border:1px solid var(--line);background:transparent;padding:13px;font:inherit;font-size:12px}.lux-form button{border:0;background:var(--ink);color:var(--sand);padding:14px;font-size:11px}.lux-success{color:var(--sage)!important}
        @media(max-width:760px){.lux-header{height:66px}.lux-nav{display:none;position:absolute;left:0;right:0;top:66px;padding:20px 25px;background:var(--sand);border-bottom:1px solid var(--line);flex-direction:column;gap:18px}.lux-nav.open{display:flex}.lux-header-actions{gap:10px}.lux-lang{display:none}.lux-menu{display:block}.lux-visit{padding:10px;font-size:10px}.lux-hero{display:block}.lux-hero-copy{padding:64px 25px 58px}.lux-hero-photo{min-height:390px}.lux-hero h1{font-size:78px}.lux-strip{flex-wrap:wrap;gap:12px}.lux-intro,.lux-method{display:block;padding:82px 25px}.lux-intro-copy{padding-top:15px}.lux-location{margin-top:30px}.lux-stock{padding:70px 25px 82px}.lux-stock-head{display:block}.lux-stock-head p{margin-top:20px}.lux-grid{display:block}.lux-card{margin-bottom:17px}.lux-card:first-child .lux-visual,.lux-visual{height:270px}.lux-method-list{margin-top:35px}.lux-footer{display:block}.lux-footer-links{margin-top:28px;flex-wrap:wrap}.lux-modal{padding:32px 24px}}
      `}</style>
      <header className="lux-header">
        <a href="#top" className="lux-brand"><span className="lux-mark">M</span><span>MYG Import<br /><small style={{ fontSize: 8, opacity: .55, letterSpacing: ".12em" }}>Luxembourg</small></span></a>
        <nav className={`lux-nav ${menuOpen ? "open" : ""}`}><a href="#selection" onClick={() => setMenuOpen(false)}>La sélection</a><a href="#maison" onClick={() => setMenuOpen(false)}>La maison</a><a href="#methode" onClick={() => setMenuOpen(false)}>Notre méthode</a></nav>
        <div className="lux-header-actions"><button className="lux-lang">FR / EN</button><button className="lux-visit" onClick={openAppointment}>Prendre rendez-vous</button><button className="lux-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Ouvrir le menu">≡</button></div>
      </header>
      <main>
        <section className="lux-hero"><div className="lux-hero-copy"><div className="lux-kicker">Automotive studio · Luxembourg</div><h1>Le beau<br /><em>cadre.</em></h1><p className="lux-hero-deck">Des automobiles choisies avec précision, dans un écrin à la mesure de leur histoire.</p><div className="lux-hero-actions"><a className="lux-button" href="#selection">Voir la sélection</a><a className="lux-button ghost" href="#maison">Découvrir la maison</a></div></div><div className="lux-hero-photo" /><div className="lux-hero-stamp">Kirchberg · Luxembourg City</div></section>
        <div className="lux-strip"><span>Ouvert du mardi au samedi</span><strong>Visites privées sur rendez-vous</strong><span>12, rue des Métiers · Luxembourg</span></div>
        <section className="lux-intro" id="maison"><div><div className="lux-eyebrow">Une adresse, une allure</div><h2>Le showroom<br />au cœur de<br /><em>la ville haute.</em></h2></div><div className="lux-intro-copy">Dans le calme minéral de notre maison luxembourgeoise, chaque voiture est présentée comme une pièce à part. La pierre, la lumière, le silence : tout est pensé pour laisser parler l’essentiel.<strong>Une sélection européenne. Une relation locale.</strong><div className="lux-location"><span>49°37′N, 6°08′E</span><span>Depuis 2018</span></div></div></section>
        <section className="lux-stock" id="selection"><div className="lux-stock-head"><div><div className="lux-eyebrow">Disponible maintenant</div><h2>La sélection.</h2></div><p>Quelques modèles rares, prêts à rejoindre une nouvelle histoire.</p></div><div className="lux-filters">{["La sélection", "Sportives", "Grand tourisme"].map((item) => <button key={item} className={`lux-filter ${active === item ? "active" : ""}`} onClick={() => setActive(item)}>{item}</button>)}</div><div className="lux-grid">{vehicles.map((vehicle, index) => <article className="lux-card" key={vehicle.name}><div className="lux-visual"><img src={vehicle.image} alt={vehicle.name} /><span className="lux-card-badge">{index === 0 ? "Coup de cœur" : index === 1 ? "Disponible" : "À découvrir"}</span></div><div className="lux-card-body"><div className="lux-card-meta"><span>{vehicle.subtitle.split(" · ")[0]}</span><span>{vehicle.subtitle.split(" · ")[1]}</span></div><h3>{vehicle.name}</h3><div className="lux-card-detail">{vehicle.detail}</div><div className="lux-card-foot"><span className="lux-price">{vehicle.price}</span><button className="lux-more" onClick={() => setSelected(vehicle)}>Voir la fiche →</button></div></div></article>)}</div></section>
        <section className="lux-method" id="methode"><div><div className="lux-eyebrow">Le parcours MYG</div><h2>Du premier<br />regard au<br /><em>dernier tour.</em></h2></div><div className="lux-method-list">{[["01", "Écouter", "Une conversation simple pour comprendre vos envies, votre quotidien, et le détail qui compte."], ["02", "Sourcer", "Notre réseau traverse l'Europe. Nous ouvrons les bonnes portes et vérifions chaque histoire."], ["03", "Préparer", "Contrôle complet, conformité et livraison au Luxembourg. Le plaisir commence avant la route."]].map(([number, title, copy]) => <div className="lux-method-item" key={number}><b>{number}</b><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div></section>
        <section className="lux-quote"><blockquote>« La meilleure route est parfois celle qui commence dans une cour de pierre. »</blockquote><cite>La philosophie MYG Import</cite></section>
      </main>
      <footer className="lux-footer"><div className="lux-footer-brand">MYG Import<small>Automotive studio · Luxembourg</small></div><div className="lux-footer-links"><a href="#selection">Collection</a><a href="#methode">Notre méthode</a><button onClick={openAppointment}>Parler à un expert</button></div></footer>
      {selected && <div className="lux-modal-backdrop" onClick={() => setSelected(null)}><div className="lux-modal" onClick={(event) => event.stopPropagation()}><button className="lux-modal-close" onClick={() => setSelected(null)}>×</button><div className="lux-eyebrow">Fiche véhicule</div><h2>{selected.name}</h2><p>{selected.subtitle}<br />{selected.detail} · {selected.price}</p><p>Présenté dans notre showroom de Luxembourg. Disponible pour une visite privée.</p><button className="lux-button" onClick={openAppointment}>Organiser une visite</button></div></div>}
      {appointment && <div className="lux-modal-backdrop" onClick={() => setAppointment(false)}><form className="lux-modal" onClick={(event) => event.stopPropagation()} onSubmit={(event) => { event.preventDefault(); setSent(true); }}><button type="button" className="lux-modal-close" onClick={() => setAppointment(false)}>×</button>{sent ? <><div className="lux-eyebrow">Demande reçue</div><h2>À très bientôt.</h2><p className="lux-success">Merci. Notre équipe vous recontactera dans les 24 heures pour confirmer votre visite à Luxembourg.</p><button type="button" className="lux-button" onClick={() => setAppointment(false)}>Fermer</button></> : <><div className="lux-eyebrow">Votre projet automobile</div><h2>Entrons en<br /><em>conversation.</em></h2><p>Un premier échange, sans pression, dans notre showroom de Kirchberg.</p><div className="lux-form"><input required placeholder="Votre nom" aria-label="Votre nom" /><input required type="email" placeholder="Votre adresse email" aria-label="Votre adresse email" /><input placeholder="Le modèle qui vous intéresse (optionnel)" aria-label="Modèle" /><button>Demander un rendez-vous</button></div></>}</form></div>}
    </div>
  );
}